### ISSUE TITLE
Missing `disabled-text-color`

### ISSUE THREAD

**Issue by wcork** [chaptergy/noctis-grey#4]
Disabled icons and text are hard to differentiate from enabled ones.
Adding `disabled-text-color: '#626569'` (The value in `noctis`) fixes this.

**Comment by chaptergy** [comment]
Great suggestion! Weirdly enough this color is used for the caret of dropdown menus, but I think this will be fine there as well.

**Comment by chaptergy** [comment]
Implemented in release [v1.3.2](https://github.com/chaptergy/noctis-grey/releases/tag/v1.3.2)
