### ISSUE TITLE
Mobile noctis-grey no text in settings anymore

### ISSUE THREAD

**Issue by Jo-Jo1987** [chaptergy/noctis-grey#5]
Mobile version does not show white text anymore in settings and also in automations.

**Comment by chaptergy** [comment]
Unfortunately I am not able to replicate the issue you are describing. Are you on the newest version of home assistant? Which browser do you use? Could you provide some screenshots?

**Comment by Jo-Jo1987** [comment]
I think i fixed it by just cleaning my whole home assistant and restoring it from scratch. New cookies and everything is fine now.
