### ISSUE TITLE
Incorrect border around cards since HA 2022.11

### ISSUE THREAD

**Issue by marcis92** [chaptergy/noctis-grey#6]
Since HA 2022.11 borders are shown around the cards instead of shadows and as a result it looks like this:

![image](https://user-images.githubusercontent.com/76939141/202830477-44a3bbef-5242-4170-aa8d-8881da5e3e59.png)

Solution would be pretty simple:

Remove line 61:
```
border-color: 'none'
```

And add these ones:
```
ha-card-border-color: 'rgba(0,0,0,0)'
ha-card-border-width: '0'
```

Result:
![image](https://user-images.githubusercontent.com/76939141/202830706-9e5a2b87-222c-490a-85b9-d3e77cc791af.png)

**Comment by chaptergy** [comment]
Fixed in https://github.com/chaptergy/noctis-grey/releases/tag/v1.3.4
