### ISSUE TITLE
Dark icons on dark background in Traces menu

### ISSUE THREAD

**Issue by mfhunruh** [chaptergy/noctis-grey#7]
Hello! 

Thanks for your work! I noticed a small bug. I am using HA 2023.1 with noctis-grey v1.3.4 theme. When I open Traces in Automations, the highlighted trace has dark icons on a dark background, making it hard to see.

![Screenshot_20230129-010408~2](https://user-images.githubusercontent.com/61690629/215293752-d6267ebd-14ec-419c-a760-37db896a31c4.jpg)

This is an example of a default theme:
![Screenshot_20230129-010313](https://user-images.githubusercontent.com/61690629/215293812-cf840290-c044-43ae-8bbb-cd49018bda7e.jpg)

**Comment by chaptergy** [comment]
Okay, so I didn't get a different background color to work, but I can change the icon color.

**Comment by chaptergy** [comment]
Fixed via https://github.com/chaptergy/noctis-grey/commit/2bbc45d3922c56f0d84d281d8c823fa2071538e3 in [v1.3.5](https://github.com/chaptergy/noctis-grey/releases/tag/v1.3.5)
